<?php 
    ob_start();
    $title = 'Editar cadastro';
?>

<div class="background-form">

    <form id="form-edit" action="/edit" method="POST"> 
        <h1 class="h1-form">Editar cadastro</h1>

        <input name="id" type="text" value="<?= $_SESSION['user']['id']?>" hidden>

        <label class="label-form" for="name">Nome</label>
        <input id="name" name="name" type="text" class="input-form" value="<?= $_SESSION['user']['name']?>" required>

        <label class="label-form" for="last_name">Sobrenome</label>
        <input id="last_name" name="last_name" type="text" class="input-form" value="<?= $_SESSION['user']['last_name']?>" required>

        <label class="label-form" for="email">E-mail</label>
        <input id="email" name="email" type="email" class="input-form" value="<?= $_SESSION['user']['email']?>">

        <!-- Checkbox collapse -->
        <div class="form-check my-3">
            <input class="form-check-input" type="checkbox" id="togglePassword">
            <label class="form-check-label" for="togglePassword">Alterar senha</label>
        </div>

        <!-- Inputs collapse -->
        <div class="collapse" id="passwordFields">
            <div class="mb-3">
                <label class="label-form" for="current_password">Senha atual</label>
                <input id="current_password" name="current_password" type="password" class="input-form">
            </div>
            <div class="mb-3">
                <label class="label-form" for="new_password">Nova senha</label>
                <input id="new_password" name="new_password" type="password" class="input-form">
            </div>
        </div>

        <div class="button-container">
            <button type="submit" class="button-submit">Editar</button>
        </div>
    </form>

    <a href="/home" class="link-redirect">Voltar a tela principal</a>
</div>

<?php 
    $content = ob_get_clean();
    
    require_once('../Public/layouts/template.phtml');
?>

<script>
    // Habilita o collapse via checkbox
    const checkbox = document.getElementById('togglePassword');
    
    const collapse = new bootstrap.Collapse(document.getElementById('passwordFields'), { toggle: false });

    checkbox.addEventListener('change', function () {
        if (this.checked) {
            collapse.show();
        } else {
            collapse.hide();
        }
    });
</script>