<?php 

    $title = 'Esqueceu sua senha?';
    ob_start();

?>

<div class="background-form">

    <form id="" action="/" method="POST"> 
        <h1 class="h1-form">Esqueceu sua senha?</h1>

        <label class="label-form" for="email">Digite seu e-mail</label>
        <input id="email" name="email" type="text" class="input-form" required>

        <div class="button-container">
            <button type="submit" class="button-submit">Confirmar</button>
        </div>

    </form>

</div>

<?php 

    $content = ob_get_clean();

    require_once('../Public/layouts/template.phtml');

?>