<?php 
    $title = "Login";
    
    ob_start();
?>

<div class="background-form">

    <form id="form-register" action="/" method="POST"> 
        <h1 class="h1-form">Login</h1>

        <label class="label-form" for="email">Usuário</label>
        <input id="email" name="email" type="text" class="input-form" value="<?= isset($email) ? $email : '' ?>" required>

        <label class="label-form" for="password">Senha</label>
        <input id="password" name="password" type="password" class="input-form" required>

        <div class="button-container">
            <button type="submit" class="button-submit">Login</button>
        </div>

        <a href="/register" class="link-redirect">Não tem uma conta? Cadastre-se agora!</a>
    </form>

</div>

<?php 

    $content = ob_get_clean();
    
    require_once('../Public/layouts/template.phtml');
?>
