<?php 

    ob_start();

?>

<div class="background-form">

    <form id="" action=<?= $action ?> method="POST"> 
        <h1 class="h1-form"><?= $form_title ?></h1>

        <label class="label-form" for="cod"><?= $form_label ?></label>
        <input id="<?= $input_name ?>" name="<?= $input_name ?>" class="input-form" required>

        <div class="button-container">
            <button type="submit" class="button-submit">Confirmar</button>
        </div>

    </form>

</div>

<?php 

    $content = ob_get_clean();

    require_once('../Public/layouts/template.phtml');

?>