<?php 
    $title = "Cadastrar";
    ob_start();
?>

<div class="background-form">

    <form id="form-login" action="/register" method="POST"> 
        <h1 class="h1-form">Cadastre-se</h1>

        <label class="label-form" for="name">Nome</label>
        <input id="name" name="name" type="text" class="input-form" required value="<?= isset($name) ? $name : '' ?>">

        <label class="label-form" for="last_name">Sobrenome</label>
        <input id="last_name" name="last_name" type="text" class="input-form" required value="<?= isset($last_name) ? $last_name : '' ?>" >

        <label class="label-form" for="email">E-mail</label>
        <input id="email" name="email" type="email" class="input-form" required value="<?= isset($email) ? $email : '' ?>" >

        <label class="label-form" for="password">Senha</label>
        <input id="password" name="password" type="password" required class="input-form">

        <label class="label-form" for="password_repeat">Repita a senha</label>
        <input id="password_repeat" name="password_repeat" type="password" required class="input-form">

        <div class="button-container">
            <button type="submit" class="button-submit">Cadastrar</button>
        </div>

        <a href="/" class="link-redirect">Já tem uma conta? Entre agora!</a>
    </form>
    
</div>

<?php 
    $content = ob_get_clean();

    require_once('../Public/layouts/template.phtml');
?>
