<?php 
    $title = "Cadastrar";
    ob_start();
?>

<div class="background-form">

    <form id="form-login" action="/register" method="POST"> 
        <h1 class="h1-form">Cadastre-se</h1>

        <label class="label-form" for="name">Nome</label>
        <input id="name" name="name" type="text" class="input-form" required>

        <label class="label-form" for="last-name">Sobrenome</label>
        <input id="last-name" name="last-name" type="text" class="input-form" required>

        <label class="label-form" for="email">E-mail</label>
        <input id="email" name="email" type="email" class="input-form" required>

        <label class="label-form" for="password">Senha</label>
        <input id="password" name="password" type="password" class="input-form" required>

        <label class="label-form" for="repeat-password">Repita a senha</label>
        <input id="repeat-password" name="repeat-password" type="password" class="input-form" required>

        <div class="button-container">
            <button type="submit" class="button-submit">Cadastrar</button>
        </div>

        <a href="/" class="link-redirect">Já tem uma conta? Entre agora!</a>
    </form>

    <?php if (isset($error_message)): ?>
        <p><?= $error_message ?></p>
    <?php endif; ?>

</div>

<?php 
    $content = ob_get_clean();
    require_once('../Public/layouts/template.phtml');
?>
