<?php 
    $title = "Cadastrar";
    ob_start();
?>

<div class="background-form">

    <form id="form-login" action="/register" method="POST"> 
        <h1 class="h1-form">Cadastre-se</h1>

        <label class="label-form" for="name">Nome</label>
        <input id="name" name="name" type="text" class="input-form" required>

        <label class="label-form" for="last_name">Sobrenome</label>
        <input id="last_name" name="last_name" type="text" class="input-form" required>

        <label class="label-form" for="email">E-mail</label>
        <input id="email" name="email" type="email" class="input-form" required>

        <label class="label-form" for="password">Senha</label>
        <input id="password" name="password" type="password" class="input-form" required>

        <label class="label-form" for="repeat_password">Repita a senha</label>
        <input id="repeat-password" name="repeat-password" type="password" class="input-form" required>

        <div class="button-container">
            <button type="submit" class="button-submit">Cadastrar</button>
        </div>

        <a href="/" class="link-redirect">Já tem uma conta? Entre agora!</a>
    </form>
    

</div>

<?php 
    $content = ob_get_clean();

    if (isset($_GET['error']) && isset($_GET['type']))
    {
        if ($_GET['type'] == 'user_exists')
        {
            $message_alert = 'E-mail já cadastrado!';
        }
        else if($_GET['type'] == 'missing_field')
        {
            $message_alert = 'Preencha todos os campos obrigatórios!';
        }
    }

    require_once('../Public/layouts/template.phtml');
?>
